Isn-t-this-E-not-I/Now-WayPoint-BE

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/member/Member.java
- now-waypoint-mysql/init/create_table.sql
> test: github action

- .idea/.gitignore
- .idea/Now-WayPoint-BE.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- docker-compose.yml
- now-waypoint-core/Dockerfile
- now-waypoint-core/build.gradle
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/dto/UserRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/exception/InvalidAuthException.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/exception/NullFieldException.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/exception/exhandler/LoginExceptionHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLoginFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLogoutService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/User.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/CorsConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-mysql/init/create_table.sql
- 회원 로그아웃시 토큰 제거, 탈퇴 시 정보 삭제 구현
- docker환경에서 버그 발생하여 core서버 포트 변경
- 유저 확인을 위한 users Entity 생성
> feat : 회원 로그아웃, 탈퇴 기능 구현

- now-waypoint-core/src/main/resources/application.properties
> 📌 fix  : 포트 변경 80 -> 8080

- docker-compose.yml
- now-waypoint-core/build.gradle
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/exception/LogoutFailException.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLoginFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserDetail.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/resources/application-dev.properties
- now-waypoint-core/src/main/resources/application-prod.properties
- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-mysql/init/create_table.sql
- 카카오 로그인 시 발급된 토큰으로 get요청 에러 수정
- properties: dev,prod redis setting
>  📌fix : 카카로 로그인 사용자 get요청 에러 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLoginFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- 리프레쉬 토큰이 있어도 어세스 토큰이 발급이 안되던 에러 수정
- 점심시간에 올려서 죄송합니다..ㅠ
> 📌fix : 어세스토큰 재발급 에러 수정

- .idea/.name
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/modules/now-waypoint-core.main.iml
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/AddressController.java
- now-waypoint-core/src/main/resources/application-dev.properties
- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-core/src/main/resources/templates/map/homeMap.html
- now-waypoint-core/src/test/java/isn_t_this_e_not_i/now_waypoint_core/URLEncoderTest.java
> ✨ feat : 카카오 맵 api 사용 --> get 사용하여 위치의 위도 경도 정보 가져오기

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/EmbeddedRedisConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/MapController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/service/MapService.java
- now-waypoint-core/src/main/resources/application-dev.properties
- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-core/src/test/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/URLEncoderTest.java
> 💡refactor : MapApi 코드리팩토링

- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-core/src/test/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/RedisConfigTest.java
> 🚨ci : properties profile prod

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostCategory.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/exception/ResourceNotFoundException.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/exception/UnauthorizedException.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FEAT: 게시글 CRUD

- now-waypoint-core/build.gradle
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLoginFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtStompHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/CorsConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/WebSocketConfig.java
- now-waypoint-core/src/test/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/WebSocketConnectTest.java
> ✨feat: websocket Security 설정 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
> 💡refactor: userInfoPage

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FIX : 'loginId' 기반으로 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/LikeUserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Like.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/LikeRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/HashtagService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/LikeService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FEAT: 좋아요 기능 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/WebSocketConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- follower에게 실시간 게시글 전송(stomp)
> ✨ feat : follower에게 실시간 게시글 전송

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLoginFilter.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtStompHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtUtil.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/MainController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
>  ✨ feat : 유저별로 게시글 전체조회, 카테고리별 조회

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
> FIX: updateAt 제거

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRedisRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- ✨ feat : redis사용 게시글 전체조회, 카테고리 조회
> ✨ feat : redis사용 게시글 전체조회, 카테고리 조회

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/dto/request/CommentRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/dto/response/CommentResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/entity/Comment.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/repository/CommentRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
기본적인 댓글 기능을 추가하였습니다. 이후에 추가적 기능을 개발하여 PR 하겠습니다.
> FEAT: 댓글 기본 기능

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
> 💡refactor: oauth2 프론트엔드로 경로 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
> 💡refactor: 카카오 로그인 헤더 토큰

- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-mysql/init/create_table.sql
> test: auto CD

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/exception/exhandler/LoginExceptionHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SwaggerConfig.java
- now-waypoint-core/src/main/resources/application.properties
- 토큰 기간 일주일 설정
- swagger token값 설정
> 🔨build: token 기간 설정, swagger token 설정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/mail/service/EmailAuthService.java
> 💡refactor: email전송 loginId

- now-waypoint-core/build.gradle
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/LocationController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/MapController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/service/MapService.java
> 📌fix : 프론트에서 geolocation 사용하여 위도, 경도를 백으로 보내고 해더값에 데이터 저장

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
> build: 카카오 로그인 email추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FIX: mediaUrl을 LIST로 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
> FIX : POST에 닉네임, 프로필 이미지 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/entity/CommentLike.java
- now-waypoint-mysql/init/create_table.sql
>  refactor : id -> comment_like_id , add table

- now-waypoint-mysql/init/create_table.sql
> feat : comment, comment_like table

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/mail/service/EmailAuthService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/RedisConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/MapController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/service/MapService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostCategory.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/exception/PostExceptionHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRedisRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-mysql/init/create_table.sql
- 위도 경도 기반 100m내 게시글 조희
- 100m내 카테고리별 게시글 조회
- email전송 오류 수정
> feat: 사용자의 위도 경도기반으로 100m내 게시글 카테고리별 조회

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserDetail.java
- Cookie 넘기는 방식 변경 배포 서버에서 되는지 test
> test: Cookie Test

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/resources/application-prod.properties
> test: Cookie Test2

- now-waypoint-mysql/init/create_table.sql
> feat : post_media_urls table

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/service/MapService.java
> test: 위도,경도 변환

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor : 위도,경도 설정값

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/service/MapService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 위도 경도 설정 배포

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor : 개발 서버 반경 100km, 게시글 시간 5시간

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240725 개발 설정 배포

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
> refactor: userInfo user의 email반환

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
- refactor: userInfo user loginId 반환, profile, nickname api 추가
> refactor: userInfo user loginId 반환, profile, nickname api 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
> 20240726 유저정보 변경 업데이트

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> refactor: profileImage 파일로 받기

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> 20240726 프로필 이미지 파일로받기

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/CorsConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/LocationController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/MapController.java
>  refactor: CORS 설정 프론트 생성 도메인 추가 설정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/CorsConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/LocationController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/map/controller/MapController.java
> 20240729 배포된 프론트와 연결

- now-waypoint-core/src/main/resources/application-prod.properties
- 카카오 redirect url설정
- cookie domain 설정
> feat: 카카오 로그인 설정

- now-waypoint-core/src/main/resources/application-prod.properties
> 20240729 카카오 로그인

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
> fix: UserFollowService

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/resources/application-prod.properties
> 20240730 userPage fix

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserFollowerRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserFollowingRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/UserFollower.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/UserFollowing.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
-회원 탈퇴 시 관련되 follow 갱신
-닉네임 변경 시 follow 유지
> feat: 팔로워 관련 기능 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserFollowerRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserFollowingRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/UserFollower.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/UserFollowing.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/resources/application-prod.properties
> 20240731 팔로워 기능

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
> feat: 전체 회원 조회 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat: follow한 유저의 게시글 전송 경로 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserFollowController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- 다른 유저의 follower,following목록 조회
- follow한 유저의 게시글 조회 시간 순 20개 조회
> feat: 다른 유저의 follower,following목록 조회

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/MessageType.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatmessage/response/ErrorMessageResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/CreateChatRoomResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/ChatMessageService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
refactor: ChatMessageService클래스 saveMessage메서드에서 StompMessageResponse를 ChatMessageResponse로 변환, MessageType에 LIST삭제, DELETE,ERROR추가, UserChatRoomService클래스 createChatRoom메서드 ErrorMessageResponse작성,  invite, leave, updateChatRoomName Response데이터 수정
> 💡refactor: 채팅 Response 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/repository/CommentLikeRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/repository/CommentRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
> FEAT : 부모 댓글 삭제시 대댓글도 함께 삭제

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-mysql/init/create_table.sql
- 알람 정렬을 위해 notify, notifyDTO에 createDate 추가
> feat: notify, notifyDTO에 createDate 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
댓글 작성 시:
멘션된 사용자에게 알림 전송: 댓글 내용에 멘션된 사용자에게 알림이 전송됩니다.
게시글 작성자에게 알림 전송: 댓글이 작성된 게시글의 작성자에게 알림이 전송됩니다.
댓글 좋아요 시:
댓글 작성자에게 알림 전송: 댓글에 좋아요를 누른 경우 해당 댓글의 작성자에게 알림이 전송됩니다.
게시글 좋아요 시:
게시글 작성자에게 알림 전송: 게시글에 좋아요를 누른 경우 해당 게시글의 작성자에게 알림이 전송됩니다.
> FEAT : 게시글, 댓글 알림

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
> FIX:약간의 이슈 ㅋ

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 8월 1일 알림 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat: notifyDTO에 id 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240801 notify 추가 설정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat: notifyDTO에 id 추가 사소한 오류..

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240801 사소한 이슈..

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/dto/response/CommentResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
> FEAT : 댓글 좋아요 상태 Boolean

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/NotifyController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- notify 조회 로직 추가
- notiry 삭제 로직 추가
> feat: 유저 notify 조회, 삭제 로직 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
> feat: 유저 notify 조회

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/NotifyController.java
> test: notify delete 오류 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/NotifyController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
> 20240802 새벽 2시..

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/controller/ChatController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatmessage/response/ChatMessageListResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/ChatMessageService.java
refactor: 채팅 메시지 전송 Mappgin주소 수정("/" 추가), 날짜코드 서울로 설정, 채팅메시지 리스트 dto 추가
> response데이터 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserFollowController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor: followList message -> api로 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserFollowController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor: 시간관계없이 팔로워의 게시글 최대 20개 반환

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserFollowController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240802 팔로워 게시글 시간제한없이 20개 가져오기

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/controller/ChatController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/ChatMessageService.java
refactor: 채팅 메시지 전송 발신자에게도 데이터가 넘어가게 리팩토링, saveMessage를 void로 형 변환
> 메시지 전송 로직 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FIX : Update 사진 삭제 removeMedia

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor: 카테고리 경로 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/MainController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRedisRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- now-waypoint-mysql/init/create_table.sql
> feat: 게시글 삭제 시 postRedis에서도 삭제

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- 게시글 삭제 시 redis게시글 관련 오류 수정
- S3 CORS권한 설정
>  feat : S3 CORS권한 설정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor: 알람, 게시글 아시아 시간 기준으로 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/User.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
-알람에 postId 추가 반환
-유저 로그인 아이디 Email형식 삭제
> feat: 알람에 postId 추가 반환

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
> refactor: 알람에 postId 추가 반환

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/dto/request/CommentRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor: notify에 postId추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- 멘션 db 저장 오류 수정
- 게시글 수정 시 알람 x
> fix: 멘션시 DB저장 오류, 게시글 수정 시 알람 o -> x

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- 카테고리와 거리를 이용하여 실시간 데이터 업데이트를 위한 필드 추가
> feat: postResponseDTO distance 필드 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
-postResponseDTO distance 필드 제거, 구독 경로 추가
> feat: postResponseDTO distance 필드 제거, 구독 경로 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240805 구독 경로 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- postResponseDTO distance 필드 추가 2트
> feat: postResponseDTO distance 필드 추가 2트

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/controller/ChatController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/MessageType.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/ChatRoomListResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/ChatRoomUserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/InviteChatRoomResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/LeaveRoomResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/UpdateRoomNameResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
refactor:
ChatController: 채팅방 목록조회 메서드명 변경, 중복 채팅방 생성 메서드 삭제 및 채팅방 생성 메서드 수정 ChatRoomUserResponse로 채팅방 생성, 채팅방 나가기, 채팅방 목록 조회 메서드에서는 채팅방안 모든 유저들의 정보(닉네임, 프로필url)을 넘겨주고, 유저 초대에서는 입력받은 유저들의 정보만 넘겨준다. StompMessageResponse 대신 생성,초대,나가기,채팅방 이름바꾸기 dto를 추가
> refactor: 채팅 유저데이터 전달, dto수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/controller/ChatController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/MessageType.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/ChatRoomListResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/ChatRoomUserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/InviteChatRoomResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/LeaveRoomResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/dto/chatroom/response/UpdateRoomNameResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponseDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
> 20240806 채팅 유저데이터 전달, dto 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/exception/InvalidPostContentException.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/exception/PostExceptionHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FIX : 게시글 공백일 경우 작성 X

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
> refactor: 중복된 채팅방 찾기 로직 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 게시글 내용 공백은 허용

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> FEAT : 게시글 내용 찐막

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
> feat: 아이디 중복 확인 api

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240806 로그인아이디 중복확인 api

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> feat: 아이디 중복 확인 api security설정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
> feat: 아이디 중복 확인 api method

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> 20240806 method 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- notify,notifyDTO mediaUrl 추가
> feat: notify,notifyDTO mediaUrl 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240807 notify media url 데이터 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
refactor: 중복된 채팅방 찾기 로직 수정, inviteUser메서드에 이미 존재하는 유저를 제외한 유저 초대
> 채팅방 생성, 유저 초대 로직 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat: notify,notifyDTO comment 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/dto/NotifyDTO.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240807 notify data 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/mail/controller/EmailController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserRequest.java
> feat: email check api 분리

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/NotifyController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
> feat: 알람 전체 삭제 api 생성

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> refactor: 게시글 작성 메세지 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLogoutService.java
> feat: 로그아웃시 쿠키의 토큰,닉네임 제거

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLogoutService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
> 20240808 로그아웃시 쿠키 제거

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/TokenService.java
- oauth2로그인시 token과 nickname반환 경로 수정
> feat: oauth2로그인시 token과 nickname반환 경로 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtLogoutService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/TokenService.java
> 20240808 oauth2 토큰 반환 경로 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
-oauth2로그인시 token과 nickname반환 경로 수정 security 수정
> feat: oauth2로그인시 token과 nickname반환 경로 수정 security 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
> refactor: 댓글 좋아요 postId 받는 법 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/controller/CommentController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> 20240808 댓글 좋아요 알림 postId 받는 방법 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/MainController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- 회원가입 시 사용할 주위 유저 찾기 api 생성 (반경 100km)
> feat: 유저 주위의 유저찾기 api 생성

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserRepository.java
> fix: 유저 위치 찾기 query

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/handler/OAuth2SuccessHandler.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserDetailService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserDetail.java
> feat: 카카오 첫 로그인, 로그인 구별 로직

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
refactor: updateUserNicknameInChatRooms메서드에서 채팅방에 존재하는 모든 유저에게 닉네임 업데이트 정보 전송 추가
> 닉네임 변경시 채팅방에 속한 모든 유저들에게 데이터 전송

- .github/workflows/prod-deploy.yml
> 20240812 닉네임 변경시 채팅방 유저들에게 데이터 전송

- now-waypoint-core/src/main/resources/application.properties
> build: docker image 생성

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/chat/service/UserChatRoomService.java
- now-waypoint-core/src/main/resources/application.properties
> 20240812 배포

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserFollowController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/User.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/user/dto/UserResponse.java
- now-waypoint-core/src/main/resources/application.properties
> 20240812 유저 active api 추가

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> feat: security Config설정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/repository/UserFollowerRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRedisRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- now-waypoint-core/src/main/resources/application.properties
- now-waypoint-mysql/init/create_table.sql
- 간편로그인 정보 로그인 업데이트 삭제
- 회원탈퇴 시 지도 게시글 삭제
- 회원탈퇴 시 follower목록 삭제
> fix : 간편로그인 업데이트 삭제, 회원탈퇴 오류 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
> fix: 카카오 로그인 오류

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRedisRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> fix: 좋아요 좋아요/취소 시 postRedis 업데이트

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/PostRedis.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRedisRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostRedisService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240822 카테고리 게시글 좋아요 시 업데이트

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/dto/OAuth2UserResponse.java
> feat: 카카오 로그인 시 유저 email 반환

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
> fix: 소셜 로그인 시 active값 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/dto/OAuth2UserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/resources/application-prod.properties
- now-waypoint-core/src/main/resources/application.properties
> fix: 네이버 간편 로그인 구현

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/dto/OAuth2UserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
- now-waypoint-core/src/main/resources/application-prod.properties
- now-waypoint-core/src/main/resources/application.properties
> 20240826 네이버 간편 로그인 구현

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/dto/OAuth2UserResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/oauth2/service/OAuth2UserService.java
> fix: 네이버 로그인 name, nickname

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtFilter.java
> feat : token auth 검증 api

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/resources/application.properties
> fix: 엑세스토큰 하루

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/jwt/JwtFilter.java
- now-waypoint-core/src/main/resources/application.properties
> 20240908 accessToken 해결, 자동로그아웃

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserFollowController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/config/SecurityConfig.java
> fix: logout Actice 변경 token값에서 nickname으로 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/NotifyController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
-  notify read 추가
-  read count api
-  change count api 생성
> feat : notify read 추가, read count api/ change count api 생성

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat : notify read -> isRead

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserFollowService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/comment/service/CommentService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/controller/NotifyController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/entity/Notify.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> 20240910 알림 column명 변경

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/controller/UserController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/HashtagSet.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/HashtagSetRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/HashtagService.java
> faet : hashtagSet 엔터티 생성

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/BookmarkController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Bookmark.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/BookmarkRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/BookmarkService.java
> feat : 북마크 기능

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Bookmark.java
> fix: bookmark_id 컬럼 생성

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/controller/MeetingController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/dto/MeetingRequestDto.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/entity/Meeting.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/repository/MeetingRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/service/MeetingService.java
> feat : 모임 기능 추가(생성, 조회, 삭제)

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/BookmarkService.java
북마크 등록 시 상대방에게 알림이 가는 기능을 삭제하였습니다.
> fix: 북마크 알림 삭제

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/repository/NotifyRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/main/service/NotifyService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
- now-waypoint-mysql/init/create_table.sql
> fix : 게시글 삭제시 해당 게시글 알림 삭제

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> fix : 게시글 작성 알림 content 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
1. #기호로 시작
1. 밑줄(_) 유일하게 허영되는 특수문자
2. 공백 또는 특수문자 포함 금지
3. 숫자 및 문자 혼합 가능
4. 최대길이 30자
5. 중복 허용
> fix : 해시태그 기능 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
#기호로 시작
밑줄(_) 유일하게 허영되는 특수문자
공백 또는 특수문자 포함 금지
숫자 및 문자 혼합 가능
최대길이 30자
중복 허용
> fix : 해시태그 api 수정

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/auth/service/UserService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/BookmarkService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
인기도 점수를 추가하여 점수가 높은 순으로 20개 정렬
> feat : popular

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/controller/MeetingController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/dto/MeetingRequestDto.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/entity/Meeting.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/service/MeetingService.java
기본적인 모임 기능(생성, 조회, 삭제) 기능 완성 + 카카오 api를 이용해서 프론트에서 string 값으로 지역이름 설정(ex. 합정동) -> 위도 경도 추출
> feat : 모임 기능(생성, 조회, 삭제) + 위치

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/controller/MeetingController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/dto/UserMeetingResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/entity/UserMeeting.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/repository/UserMeetingRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/service/MeetingService.java
feat : 유저가 참여한 모임 목록 조회 api 및 서비스 구현
> feat : 유저가 참여한 모임 목록 조회 api 및 서비스 구현

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/BookmarkController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/DraftController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/DraftRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/DraftResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Draft.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/DraftRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/HashtagRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/LikeRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/BookmarkService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/DraftService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/LikeService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat: 임시저장 api 및 리팩토링

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/controller/MeetingController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/dto/UserMeetingResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/entity/UserMeeting.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/repository/UserMeetingRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/meet/service/MeetingService.java
모임 체크, 체크 모임 목록 조회 api 및 로직 구현
> feat : 모임 체크, 체크 모임 목록 조회 api 및 로직 구현

- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/BookmarkController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/DraftController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/controller/PostController.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/DraftRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/request/PostRequest.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/DraftResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/dto/response/PostResponse.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Draft.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/entity/Post.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/DraftRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/HashtagRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/LikeRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/repository/PostRepository.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/BookmarkService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/DraftService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/LikeService.java
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> feat : 임시저장 API 및 리팩토링

- .github/workflows/now-waypoint-core.yml
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> docs : core docker 이미지 생성

- .github/workflows/now-waypoint-core.yml
- now-waypoint-core/src/main/java/isn_t_this_e_not_i/now_waypoint_core/domain/post/service/PostService.java
> deploy : 오류 수정 배포

- .github/workflows/now-waypoint-mysql.yml
- now-waypoint-mysql/init/create_table.sql
> chore : setting 변경
